### PR TITLE
Upgrade to Bevy 0.13

### PR DESCRIPTION
**Pull request by snendev**
# Changes

- Updates `bevy` dependencies from `0.12` to `0.12`
- Adds `smol_str` dev dependency in order to provide accurate logical keys in test structs. do we need to test this new property in any way?

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
I would prefer to have some tests for LogicalKey, but I won't block on it here.

**Comment by snendev** [comment]
I don't mind implementing in this PR. But I'm not sure what those tests should look like; maybe reading from `ReceivedCharacters` during playback? (Should that work as-is?)

**Comment by alice-i-cecile** [comment]
I *think* that should work. But yeah, let's do it separately :)

**Comment by snendev** [comment]
ack -- looks like I checked in a random git file I didn't realize was there from when I was trying to `cargo fmt` 🤦🏻

**Pull request merged**
