### PR TITLE
Remove FrameCount in favor of Bevy counterpart

### PR DESCRIPTION
**Pull request by snendev**
# Issues

Fixes https://github.com/Leafwing-Studios/leafwing_input_playback/issues/29 - **Use built-in frame count**

# Changes

- Replaces `FrameCount` with bevy counterpart in all places
- Updates system scheduling constraints based on new `FrameCount` behavior -- this crate's `FrameCount` was updated in `First` rather than `Last`
- Update tests to account for changes in behavior due to system scheduling differences

# Notes

Previous `FrameCount` implementation uses `saturating_` add/sub operations, but based on the [documentation for `FrameCount`](https://github.com/bevyengine/bevy/blob/main/crates/bevy_core/src/lib.rs#L81-L85), it seems that `wrapping_` would be more appropriate. I changed any `+` operators to use `wrapping_` functions to be specific for now.

Also, let me know if I have removed any intended effects of the playback tests. I tried to reflect the original intent to the best of my ability.

### CODE REVIEW

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
LGTM once the CHANGELOG is updated :)

**Comment by snendev** [comment]
@alice-i-cecile I don't see a `CHANGELOG.md` in this project. Would you like me to start one, or should I draft my notes in `RELEASES.md` for a future release?

**Comment by snendev** [comment]
Also, thanks for jumping in to help out! Sorry for the random burst of noise from my end!

**Comment by alice-i-cecile** [comment]
Ah sorry, I meant RELEASES.md! And no worries at all; it's very welcome.

**Comment by snendev** [comment]
OK -- I added a section for v0.6 and included release notes for this PR and #37 since I didn't follow suit there

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Awesome. Ping me on Discord when you think that we're ready for the release of 0.6?

**Pull request merged**
